logs:
  - name: root
    level: info
    appenders:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender

  - name: system
    level: debug
    appenders:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender